#!/usr/bin/env python3
"""
HRSG Weld Management System
Entry point for the application

This is a desktop application for managing welding operations in
Heat Recovery Steam Generator (HRSG) projects.

Author: Generated by Claude
Version: 2.1
Python: 3.8+
Framework: PyQt6
"""

import sys
import os

# Add src directory to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import Qt
from src.utils.logger import setup_logger
from src.utils.config import load_config
from src.database.connection import DBConnection
from src.ui.login_dialog import LoginDialog
from src.ui.main_window_qt import MainWindow

def main():
    """Main entry point for the application"""
    # Setup logging
    logger = setup_logger()
    logger.info("=" * 80)
    logger.info("HRSG Weld Management System - Starting Application")
    logger.info("=" * 80)

    # Load configuration
    config = load_config()
    logger.info(f"Configuration loaded: {config.get('app_name', 'HRSG Weld Management')}")

    # Initialize database connection
    try:
        db = DBConnection()
        logger.info("Database connection established successfully")
    except Exception as e:
        logger.error(f"Failed to initialize database: {e}")
        sys.exit(1)

    # Create Qt Application
    app = QApplication(sys.argv)
    app.setApplicationName("HRSG Weld Management System")
    app.setOrganizationName("HRSG Engineering")
    app.setApplicationVersion("2.1")

    # Set application-wide style
    app.setStyle("Fusion")

    # High DPI support
    if hasattr(Qt.ApplicationAttribute, 'AA_EnableHighDpiScaling'):
        QApplication.setAttribute(Qt.ApplicationAttribute.AA_EnableHighDpiScaling, True)
    if hasattr(Qt.ApplicationAttribute, 'AA_UseHighDpiPixmaps'):
        QApplication.setAttribute(Qt.ApplicationAttribute.AA_UseHighDpiPixmaps, True)

    # Show login dialog
    login_dialog = LoginDialog()
    if login_dialog.exec() == LoginDialog.DialogCode.Accepted:
        # User logged in successfully, show main window
        logger.info("User logged in successfully")
        main_window = MainWindow()
        main_window.show()

        # Start event loop
        exit_code = app.exec()
        logger.info(f"Application exiting with code: {exit_code}")
        sys.exit(exit_code)
    else:
        # User cancelled login
        logger.info("Login cancelled by user")
        sys.exit(0)

if __name__ == "__main__":
    main()
